import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': 'var(--color-outline-variant)',
        'on-secondary-container': '#4f5256',
        'on-secondary': '#f7f9fe',
        'secondary-dim': '#505358',
        'surface-container-lowest': '#ffffff',
        'on-background': 'var(--color-on-surface)',
        'tertiary-dim': '#485178',
        'background': 'var(--color-surface)',
        'on-primary-fixed-variant': '#565c65',
        'outline': 'var(--color-outline)',
        'surface': 'var(--color-surface)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'error-container': '#fa746f',
        'tertiary-container': '#c7cffe',
        'inverse-surface': '#0c0f0f',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-tertiary-fixed': '#293257',
        'surface-tint': '#595f69',
        'on-error': '#fff7f6',
        'on-tertiary': '#faf8ff',
        'on-tertiary-fixed-variant': '#464f76',
        'surface-variant': '#dfe3e4',
        'surface-bright': '#f9f9f9',
        'surface-container': 'var(--color-surface-container)',
        'secondary': '#5c5f64',
        'on-secondary-fixed-variant': '#585c60',
        'primary-dim': 'var(--color-primary-dim)',
        'on-primary-fixed': '#3a4048',
        'tertiary': '#545d85',
        'secondary-container': '#e0e2e8',
        'secondary-fixed-dim': '#d2d4da',
        'surface-dim': '#d7dbdb',
        'surface-container-low': 'var(--color-surface-container-low)',
        'on-primary': '#f7f9ff',
        'inverse-on-surface': '#9c9d9d',
        'on-primary-container': '#4c525b',
        'on-secondary-fixed': '#3c4044',
        'primary': 'var(--color-primary)',
        'on-error-container': '#6e0a12',
        'on-tertiary-container': '#3c456c',
        'on-surface': 'var(--color-on-surface)',
        'error': '#a83836',
        'tertiary-fixed': '#c7cffe',
        'secondary-fixed': '#e0e2e8',
        'error-dim': '#67040d',
        'inverse-primary': '#eef4ff',
        'tertiary-fixed-dim': '#b9c2ef',
        'primary-fixed': '#dde3ee',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'primary-container': 'var(--color-primary-container)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        tajawal: ['var(--font-tajawal)', 'sans-serif'],
        headline: ['var(--font-tajawal)', 'sans-serif'],
        body: ['var(--font-tajawal)', 'sans-serif'],
        label: ['var(--font-tajawal)', 'sans-serif'],
        custom: ['var(--font-custom)', 'var(--font-tajawal)', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}

export default config
